woowacourse-teams/2024-momo

README.md

- resolves: #1 
프론트엔드, 백엔드 폴더를 구성했어요.
DM으로 리뷰 부탁드리실게요. 🙏

[ALL] 모모, 안녕?

---

backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java

- resolves: #13 
- startTime 필드 추가
- endTime 필드 추가
지금은 괜찮지만 연관관계가 얽혀있어 추후 수정 가능성 농후

[BE] Meeting Entity 내 필드 추가

---

backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/TimeSlotRepository.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java

- resolves: #17 
타임슬롯 도메인을 테이블에서 enum 타입으로 수정한다.

[BE] 타임슬롯 도메인을 테이블에서 enum타입으로 수정

---

backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
backend/src/main/java/com/woowacourse/momo/exception/code/AttendeeErrorCode.java
backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleDateTimesResponse.java
backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleOneAttendeeDateTimesResponse.java
backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleOneAttendeeResponse.java
backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java

- resolves: #62 
- 단일  참가자의 스케줄 조회 로직 추가했습니다.
- 관련 테스트 추가했습니다.
> 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?
`ScheduleOneAttendeeDateTimesResponse` DTO명이 길어보이는데 괜찮은 내용이 있다면 추천드립니다!

[BE] 단일 참가자의 스케줄 조회 로직 추가

---

backend/src/main/java/com/woowacourse/momo/auth/dto/TokenInfo.java
backend/src/main/java/com/woowacourse/momo/config/WebConfig.java
backend/src/main/java/com/woowacourse/momo/controller/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/momo/controller/auth/AuthAttendee.java
backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeRepository.java
backend/src/main/java/com/woowacourse/momo/exception/code/AuthErrorCode.java
backend/src/main/java/com/woowacourse/momo/service/attendee/AttendeeService.java
backend/src/main/java/com/woowacourse/momo/service/auth/JwtManager.java
backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
backend/src/test/java/com/woowacourse/momo/service/auth/JwtManagerTest.java
backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java

- resolves: #82 
- 토큰 클레임에 참가자 id만을 담도록 변경하였습니다.
- `ArgumentResolver`를 구현하여 사용자 인증 책임을 분리하였습니다.

[BE] ArguementResolver를 구현하여 사용자 인증 책임을 컨트롤러로부터 분리

---

.github/workflows/discord-issue.yml
.github/workflows/discord-pull-request.yml
.github/workflows/discord-review.yml

- resolves: #108 
- 작업 현황 
- issue
- pull-request
- comment
들을 디스코드로 알림을 받을 수 있도록 설정했습니다.

[ALL] 작업 현황을 디스코드로 알림을 받기 위한 yml 파일 생성, 설정

---

backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java

- resolves: #145 
- 크로스 도메인 요청에도 쿠키를 전송할 수 있도록 Set-Cookie 헤더의 SameSite 옵션을 None으로 변경하였습니다.

[BE] 쿠키 헤더의 SameSite 옵션을 None으로 변경

---

backend/src/main/java/kr/momo/config/CorsConfig.java
backend/src/main/java/kr/momo/controller/CookieManager.java

- resolves: #164 
- `String[]` 을 `String` 으로 `join` 하지 않고 바로 `.allowedOriginPatterns()` 에 바로 전달하도록 수정
- Cookie Path 설정의 API 경로 오타 수정
None.

[BE] CORS, Cookie 설정 오류 수정

---

.github/workflows/backend-cd.yml

- resolves: #177 
`docker run` 시 포트포워드 인자 를 `80` 에서 `8080`으로 수정했습니다.
`Dockerfile`에는 이미 `EXPOSE 8080`으로 설정되어 있어 수정하지 않았습니다.
빠른 확인 후 머지 부탁드려요🙂

[BE] Docker 컨테이너 포트포워드 인자 수정

---

backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java

- resolves: #199 
로그아웃 시 발급하는 쿠키 헤더의 Path를 로그인의 쿠키 헤더와 일치하도록 설정합니다.
로그아웃 시 기존 쿠키가 만료되지 않던 문제를 해결합니다.

[BE] 로그아웃 쿠키에 Path가 누락된 문제를 해결

---

frontend/src/apis/meetings.ts
frontend/src/apis/mettingRecommend.ts
frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
frontend/src/components/Schedules/AllSchedule.tsx
frontend/src/components/Schedules/SchedulesViewer.tsx
frontend/src/components/Schedules/SingleSchedule.tsx
frontend/src/components/_common/Buttons/ToggleButton/index.tsx
frontend/src/mocks/meeting/data/earliestAllAttendeeSchedules.json
frontend/src/mocks/meeting/data/earliestPartialAttendeeSchedules.json
frontend/src/mocks/meeting/data/longTermAllAttendeeSchedules.json
frontend/src/mocks/meeting/data/longTermPartialAttendeeSchedules.json
frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.tsx
frontend/src/pages/MeetingRecommendPage/index.tsx
frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
frontend/src/pages/MeetingTimePickPage/index.tsx
frontend/src/stores/servers/meeting/mutation.ts

- resolves: #174 
급하게 하느라 CSS는 손보지 못했습니다. 추후에 리팩터링 시 구현한 디자인으로 수정해야 할 것 같아요.

[FE]약속 잠금 기능 구현 및 약속 추천 페이지 수정

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.tsx

- resolves: #207 
[적용 화면]
https://paper-mass-5ff.notion.site/TanStack-Query-devtools-0c6de3dced374e29bb8e6dd4c8f4b2ff?pvs=4
작업 사항 및 특이사항은 노션에 기록해두었습니다.
간단한 코드이니 리뷰 속도는 빠를 듯 합니다요~

[FE] TanStack Query devtools 설치

---

.github/workflows/backend-dev-cd.yml
.github/workflows/backend-dev-ci.yml
.github/workflows/backend-prod-cd.yml
.github/workflows/backend-prod-ci.yml

- resolves: #229 
- dev의 CI/CD 설정 파일이 훌륭하게 작성되어 prod 환경 설정도 이를 벤치 마킹하였습니다. (Thanks to @hw0603 @seunghye218)
- 설정 파일들의 구분을 위해 `name`에 각각 `Dev`와 `Prod`를 추가하였습니다.
- prod 서버에도 `Self-hosted-runner`가 추가하며 두 환경의 Runner를 구분하기 위해 태그를 추가하였습니다.
- 따라서 CD 설정의 `runs-on: [self-hosted, linux, ARM64, ${각각의 환경}]`로 태그로 runner를 찾도록 수정하였습니다.
🚨 만약 설정 파일 중 오류가 있다면 백엔드 CI/CD가 멈출 수도 있습니다.
> 리뷰 중점 사항: 리뷰어가 특히 집중해서 봐야 할 부분이 있나요?
CI/CD 처음 수정하다 보니 동작하지 않을까 두려움이 많습니다.
꼼꼼히 봐주시길 부탁드리며 함께 기도해주세요. 🙏

[BE] 운영 환경 추가로 인한 workflow 환경설정 추가

---

frontend/src/components/_common/Calendar/Calendar.styles.ts
frontend/src/components/_common/Calendar/index.tsx
frontend/src/constants/calendar.ts
frontend/src/hooks/useCalendarInfo/useCalendarInfo.ts
frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
frontend/src/styles/global.ts
frontend/src/styles/tokens/colors.ts
frontend/src/types/utility.ts

- resolves: #217 
- 달력 UI를 개선했어요~
아래는 개선된 내용들입니다 !:)
웬만한 개선, 엣지 케이스 대처는 한 것 같은데 자바스크립트 Date 객체가 우리나라 공휴일에 대한 정보는 제공해주지 않기 때문에, 실제 공휴일 표시는 어떻게 해야 할 지 아직 미정으로 남겨두고 다음 작업으로 넘어가봐야할 것 같아요. 만약 특정 라이브러리를 사용해서 보여준다고 하더라도 어떤 공휴일인지를 표시해줘야할 것 같아 디자인에도 변경이 있을 것 같아요. 석가탄신일, 부처님 오신 날 등 텍스트가 길어지는 경우 한정된 모바일 크기에서 어떻게 보여줘야할지도 논의해봐야할 것 같습니다.
네이버는 공휴일 아래에 표시해주고 있기는 하네요!
현재 css 로직 관련해서 해소되지 않은 고민사항들을 주석으로 남겨놓았습니다! 읽어보시고 코멘트 달아주시면 감사하겠습니다.

[FE] 캘린더 UI 개선

---

backend/src/main/java/kr/momo/controller/annotation/ApiErrorResponse.java
backend/src/main/java/kr/momo/controller/attendee/AttendeeControllerDocs.java
backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java

- resolves: #213 
- Swagger API 문서를 리팩터링합니다.
- 에러 상태 코드의 경우 해당 에러 코드와 메시지를 보여주도록 설정했습니다
- ApiErrorResponse 인터페이스에 ERROR_CODE_TABLE_HEADER 상수 추가

[BE] Swagger API 문서 리팩터링

---

backend/src/main/resources/logback-spring.xml
backend/src/test/resources/application.yml

- resolves: #249 
- `@SpringBootTest` 동작 시 local 로 돌아가던 오류를 발견하여 `test/resources/application.yml`내 test profile 활성화 설정을 추가하였습니다.
- test 동작시 불필요하게 로그가 저장되고 있었습니다. 이를 방지하기 위해`logback-spring.xml`에 `<SpringProfile>` 태그를 활용하여 테스트 환경이 설정된 경우 로그가 저장되지 않도록 하였습니다.
공식 문서는 이슈에 첨부하였으니 궁금하시다면 확인 바랍니다!

[BE] 테스트시 로그 저장하지 않도록 수정

---

backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java

- resolves: #259 
약속 정보 조회시, lastTime의 값이 `00:00`일 때, `24:00`으로 변환하여 응답합니다.

[BE] 약속 조회 응답 형식 수정

---

frontend/src/assets/images/information.svg
frontend/src/components/_common/Text/Accent/Accent.styles.ts
frontend/src/components/_common/Text/Accent/index.tsx
frontend/src/components/_common/Text/Text.stories.tsx
frontend/src/components/_common/Text/Text.styles.ts
frontend/src/components/_common/Text/Text.types.ts
frontend/src/components/_common/Text/index.tsx
frontend/src/styles/tokens/typography.ts

- resolves: #253 
- 재사용할 수 있는 Text 컴포넌트를 구현했습니다. 
위 이미지에서 확인할 수 있듯, 4가지 상황에 대한 UI를 하나의 컴포넌트를 사용해서 그릴 수 있도록 재사용할 수 있는 Text 컴포넌트를 구현했습니다. 지난 스프린트에서 정의한 디자인 토큰의 TYPOGRAPHY를 활용해서 구현했어요.
아래는 Text 컴포넌트를 구현할 때, 정의했던 컴포넌트 인터페이스에 대한 설명입니다. 
- variant
- default : 가장 기본이 되는 텍스트이며, 검은색을 사용한다.
- caption :  사용자에게 추가적인 정보를 알려주기 위해 사용되는 텍스트이며, 회색을 사용한다. 약속을 생성하기 위해 정보를 입력할 때, 추가 정보를 주기 위해서 사용하거나 / 조회 페이지에서 추가 정보를 주기 위해서 사용할 수 있다.
- warning : 사용자에게 예외 피드백, 경고를 주기 위해서 사용되는 텍스트이며, 빨간색을 사용한다. 약속을 생성하기 위해 정보를 입력할 때, 잘못된 입력을 할 경우 예외 피드백을 주기 위해서 사용할 수 있다.
- accent : ‘**페드로**님 반가워요' 에서 ‘페드로’라는 단어를 강조할 때 사용되는 텍스트이며, 모모 서비스의 주 색상인 핑크색을 사용한다.
- typo
- 디자인 토큰을 생성할 때, 만들었던 TYPOGRAPHY를 사용하며 titleBold, titileMedium,,,등 다양한 typo의 텍스트를 만들 수 있다.
- chidren(React.ReactNode)
- 텍스트 컴포넌트를 사용해서, 사용자에게 전달할 메시지
Text 컴포넌트 인터페이스의 …

[FE] 재사용할 수 있는 Text 컴포넌트 구현

---

frontend/src/apis/meetings.ts
frontend/src/assets/images/check.svg
frontend/src/assets/images/copy.svg
frontend/src/pages/MeetingLinkSharePage/MeetingLinkSharePage.styles.ts
frontend/src/pages/MeetingLinkSharePage/index.tsx
frontend/src/stores/servers/meeting/mutation.ts
frontend/src/types/meeting.ts
frontend/src/utils/clipboard.ts
frontend/src/utils/groupDates.ts

- resolves: #241 
> 백로그: https://paper-mass-5ff.notion.site/bb1b1dcf56e347f2b55df65a55ddddd5?pvs=4
[이전 디자인]
⭐️ **[현재 디자인(진짜 멋있다. 대박 완전이다.)]** ⭐️
https://github.com/user-attachments/assets/f35e0cdf-08d2-43e9-b174-1f695411c0b5
> 생성한 약속 정보를 확인할 수 있도록 구현했습니다.
- 디자인이 상당히 별로예요. 피드백 부탁드립니다.
- 년도를 어떻게 출력할지에 대해서 고민입니다. 출력 할지 말지, 한다면 어떻게 하는게 좋을지 함께 고민해주면 좋을 것 같아요.

[FE] 약속 생성 완료 페이지 개선

---

frontend/src/assets/images/attendeeCheck.svg
frontend/src/components/_common/Buttons/Button/Button.styles.ts
frontend/src/components/_common/Buttons/Button/index.tsx
frontend/src/components/_common/Buttons/TabButton/TabButton.stories.tsx
frontend/src/components/_common/Buttons/TabButton/TabButton.styles.ts
frontend/src/components/_common/Buttons/TabButton/TabButton.types.ts
frontend/src/components/_common/Buttons/TabButton/index.tsx

- resolves: #285 
재사용할 수 있는 탭 버튼 컴포넌트를 구현했습니다. 기존 공통 컴포넌트에 약간의 변경사항이 있어 PR Description에 함께 첨부합니다!
1. `customCss` props 추가
해당 props를 추가하게 된 계기는 다음과 같아요.
우선 아래와 같은 고민을 했었습니다..
> _공통 버튼 컴포넌트가 inactive 스타일을 가지고 있는 것이 좋은가?_
> _disabled, loading, outline 정도는 가지고 있을 수 있다고 생각하는데 inactive 스타일의 경우 공통 버튼 컴포넌트라기 보다는 탭 버튼의 성격이 강하니 공통 버튼 컴포넌트를 조합한 탭 버튼을 만들자._
위 고민에서 확인할 수 있듯, 공통 버튼 컴포넌트가 active 상태 즉 사용자가 선택한 버튼에 대한 스타일 책임까지 가지고 있을 필요는 없다고 생각했어요. 그래서 공통 버튼 컴포넌트를 조합하는 탭 버튼 컴포넌트를 만들고 해당 컴포넌트에서 css를 외부에서 주입할 수 있도록 했어요.
```tsx
export function Button({
variant,
borderRadius = '0.8rem',
children,
size,
disabled,
type = 'button',
onClick,
customCss,
}: ButtonProps) {
const cssProps = [s_baseButton(borderRadius), s_size(size)];
if (variant) cssProps.push(s_variant[variant]);
return (
<button disabled={disabled} …
```

[FE] 재사용할 수 있는 탭 컴포넌트 구현

---

frontend/src/components/_common/Text/Accent/index.tsx
frontend/src/pages/ErrorPage/index.tsx

[FE] Accent props 구조의 변경 사항이 반영되지 않았던 문제 해결

---

frontend/src/components/AttendeeTooltip/index.tsx
frontend/src/components/Schedules/SchedulePicker/index.tsx
frontend/src/components/Schedules/Schedules.styles.ts
frontend/src/components/_common/Tooltip/Tooltip.styles.ts
frontend/src/components/_common/Tooltip/index.tsx

- resolves: #311 
- 사용자가 선택한 시간을 강조할 수 있는 빗금 스타일 추가
- 시간 등록을 취소할 수 있는 버튼 추가
- 시간을 등록할 때 날짜를 페이지네이션할 수 있는 버튼 위치 수정

[FE] 사용자가 선택한 시간대를 강조할 수 있는 빗금 스타일 추가

---

frontend/package.json
frontend/src/index.tsx

- resolves: #321 
- dev 배포시에도 msw가 실행되었던 문제를 해결했습니다.

[FE] dev 배포시에도 msw가 실행되었던 문제 해결

---

frontend/package.json
frontend/src/index.tsx

Reverts woowacourse-teams/2024-momo#324

Revert "[FE] build:dev 스크립트에서 노드 환경을 production으로 수정"

---

.github/workflows/frontend-prod-cd.yml
frontend/package.json
frontend/src/index.tsx

- resolves: #328 
기존 frontend-prod-cd.yml 파일에서 동작하지 않았던 detect-change을 동작하도록 yml 파일을 수정했습니다.

[ALL] frontend-prod-cd.yml 파일의 detect-change job 수정

---

frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
frontend/src/components/_common/Checkbox/Checkbox.styles.ts
frontend/src/components/_common/Checkbox/index.tsx

- resolves: #358 
가장 작은 단위의 체크박스 공통 컴포넌트를 만들었습니다. 디자인적인 요소는 아직 고려하지 않았습니다. 현재 SVG를 react-icons로 대체할 가능성이 있어, 기능적으로 동작하기 위한 컴포넌트로 우선적으로 제작했습니다. 
따라서 가장 기본적인 형태의 ipnut을 통해 구현했습니다.
https://github.com/user-attachments/assets/a4d2564e-1953-43be-9f97-0e533471ddfc

[FE] 체크박스 공통 컴포넌트 구현

---

backend/src/main/java/kr/momo/config/RoutingDataSource.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java

hotfix: replica로 업데이트 쿼리 날아가던 오류 수정
- resolves: #373

[BE] replica로 업데이트 쿼리 날아가던 오류 수정

---

frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/MeetingCreationConfirmModal.styles.ts
frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/index.tsx
frontend/src/pages/CreateMeetingPage/index.tsx

- resolves: #406 
이 PR은 #414 에서 hotfix로 `main` 브랜치에 병합되었던 작업 내용을 `develop` 브랜치와 동기화하기 위한 것입니다.
#406 에서 발생한 '약속 생성 확인 모달'이 사라진 이슈를 해결하기 위해 `main` 브랜치에 직접 수정 사항을 반영했습니다. `develop` 브랜치에도 동일한 수정 사항을 적용하여, 이후의 개발 작업에 혼란이 없도록 하기 위해 본 PR을 생성하였습니다.

[FE] 약속 생성 확인 모달 복구 develop 브랜치에 적용
