backend/src/main/java/com/woowacourse/momo/MomoApplication.java
backend/src/main/java/com/woowacourse/momo/domain/BaseEntity.java
backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDate.java
backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDateRepository.java
backend/src/main/java/com/woowacourse/momo/domain/guest/Guest.java
backend/src/main/java/com/woowacourse/momo/domain/guest/GuestRepository.java
backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
backend/src/main/java/com/woowacourse/momo/domain/meeting/MeetingRepository.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/TimeSlotRepository.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java

- resolves: #8 
- BaseEntity 추가
- ERD 바탕으로 Entity 추가
- JpaRepository 추가
- 없음
- 함께 모여 합의함

[BE] Entity 설계

---

.gitignore
backend/src/main/java/com/woowacourse/momo/controller/MomoApiResponse.java

- resolves: #10 
API 응답 결과를 추상화하여 공통으로 내려 줄 응답 객체를 정의했습니다.
타입 변수 `T`에 `List<Object>` 형태의 타입 전달도 가능하므로, `SingleResponse`와 `ListResponse` 객체를 분리하지 않고 하나로 통합했습니다.
일반적으로 공통 응답 객체에는 상태코드나 메시지 등을 정의하는 경우도 있지만, 현재 단계에서는 불필요하다고 판단하여 우선 `data` 필드만 정의했습니다.
전역 `.gitignore`에 추가해야 하는 사항이 있어 수정해서 그런지 프론트 팀원분들도 같이 CODEOWNER가 적용돼서 리뷰어로 고정되네요🥲 백엔드 분들만 리뷰 주시면 될 것 같습니다!

[BE] API 공통 응답 객체 정의

---

backend/src/main/java/com/woowacourse/momo/config/CorsConfig.java

- resolves: #11 
- CORS 설정 파일 추가
- 서버 내 모든 API에 대해 CORS 허용
- 모든 출처에 대한 CORS 허용
- 모든 HTTP 메서드에 대한 CORS 허용
웹 서버 배포 후 특정 출처를 명시해야할 필요성이 있어요:)
쿠키/세션과 같은 인증 정보로 다룬다면 관련 설정을 추가해주어야 합니다.
현재 POST, GET에 대해 무리없이 동작할 것으로 예상해요

[BE] CORS Config 추가

---

backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDateRepository.java
backend/src/main/java/com/woowacourse/momo/domain/guest/Guest.java
backend/src/main/java/com/woowacourse/momo/domain/guest/GuestName.java
backend/src/main/java/com/woowacourse/momo/domain/guest/GuestRepository.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
backend/src/main/java/com/woowacourse/momo/service/schedule/dto/DateTimesCreateRequest.java
backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleCreateRequest.java
backend/src/test/java/com/woowacourse/momo/domain/guest/GuestNameTest.java

- resolves: #15 
- 원시 값 포장
- 가능 시간을 생성하는데 필요한 검증 로직 추가
- 가능 시간을 저장

[BE] 가능 시간 추가 API 구현

---

backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDateRepository.java
backend/src/main/java/com/woowacourse/momo/domain/meeting/MeetingRepository.java
backend/src/main/java/com/woowacourse/momo/domain/meeting/dto/MeetingResponse.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
backend/src/main/java/com/woowacourse/momo/domain/schedule/dto/ScheduleTimeResponse.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingResponse.java
backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java

- resolves: #16 
- 미팅의 후보 일자
- 미팅 이름
- 시작 시간과 끝 시간
- 현재 미팅에 등록된 시간들
을 조회할 수 있는 API를 작성했습니다.
이후 게스트 별 되는 시간을 조회해야 하는 기능이 추가될 것이므로 응답 객체의 `schedules` 리스트의 구조는 변경될 여지가 있습니다.
검증과 예외처리를 추가해야 하고 테스트 코드 역시 추가가 필요해 보입니다 🥲
우선 오늘까지 해커톤으로 진행되니 현재 구현만큼만 머지하고 설계를 하나씩 수정해 봐요

[BE] 미팅 기본 정보 조회 API 구현

---

backend/src/main/java/com/woowacourse/momo/exception/MomoException.java
backend/src/main/java/com/woowacourse/momo/exception/code/ErrorCodeType.java

- resolves: #28 
- 커스텀 예외로 사용할 `MomoException` 추가
- 모든 에러코드에 구현할 공통 인터페이스 추가
없습니다.

[BE] 커스텀 예외 및 에러코드 인터페이스 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/types/images.d.ts
frontend/webpack.common.js

- resolves: #43 
- **파일 모듈 선언**: 이미지 및 폰트 파일 모듈을 선언
- **이미지 파일 로더 설정**: png, jpeg, gif 파일을 처리하기 위한 로더를 추가하고, `assets/images/` 경로로 저장되도록 설정
- **폰트 파일 로더 설정**: woff, woff2, eot, ttf, otf 폰트 파일을 처리하기 위한 로더를 추가하고, `assets/fonts/` 경로로 저장되도록 설정
- **SVG 파일 로더 설정**:` @svgr/webpack`을 사용하여 SVG 파일을 React 컴포넌트로 변환하는 로더를 추가
- **성능 설정 조정**: 이미지와 폰트 파일의 크기에 대한 성능 경고를 비활성화하고, 자산 및 엔트리 포인트 크기 제한을 400,000 바이트로 조정 ([기본값 250,000 바이트](https://webpack.js.org/configuration/performance/)) 이 변경은 `npm run build` 및 `npm run prod` 실행 시 발생하는 크기 초과 경고를 해결하기 위함입니다.
- png, svg 적용해본 결과 (사용된 png, svg는 올리지 않았습니다.)
`npm run build` / `npm run prod `명령어를 실행할 때, png 이미지 파일 1장이 포함된 결과물에서 다음과 같은 두 가지 성능 관련 경고가 발생합니다.
> asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web …

[FE] Webpack에서 Assets 파일(image, SVG, font)을 빌드할 수 있도록 설정

---

frontend/src/styles/fonts.ts
frontend/src/styles/global.ts

- resolves: #46
- 각 폰트 스타일에 대해 `.woff2` 파일을 추가하였습니다.
- `@font-face` 규칙을 사용하여 'Spoqa Han Sans Neo' 폰트 패밀리를 정의하였습니다.
- Thin (100 weight)
- Light (300 weight)
- Regular (400 weight)
- Medium (500 weight)
- Bold (700 weight)
- 결과 (쉬운 결과 비교를 위해서 사파리 브라우저 테스트 사진을 첨부합니다.)
- 폰트 적용 전
- 폰트 적용 후
해당 작업과 관련된 내용을 notion에 기록해 보았습니다. [notion 링크](https://paper-mass-5ff.notion.site/font-2bdd90139f1a485cbff8e046bb1469f9?pvs=4)

[FE] 프로젝트의 기본 폰트를 Spoqa Han Sans Neo로 설정

---

.github/workflows/frontend-ci.yml
frontend/package-lock.json
frontend/package.json

- resolves: #37
`frontend` 디렉토리에 대해 GitHub Actions를 이용한 CI 워크플로우를 설정하였습니다. 
- frontend 디렉토리에 대한 변경 사항을 감지하여 CI 파이프라인을 트리거하도록 설정
- Node.js LTS 버전 설정 및 node_modules 캐싱을 통해 의존성 설치 최적화
- package-lock.json을 기반으로 의존성 설치 및 테스트 실행
- 테스트 결과를 PR에 코멘트로 등록하는 기능 추가

[FE] ci 워크플로우 구축

---

backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDate.java
backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDates.java
backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
backend/src/main/java/com/woowacourse/momo/exception/code/AvailableDateErrorCode.java
backend/src/main/java/com/woowacourse/momo/exception/code/MeetingErrorCode.java
backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingCreateRequest.java
backend/src/test/java/com/woowacourse/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/momo/domain/availabledate/AvailableDatesTest.java
backend/src/test/java/com/woowacourse/momo/domain/meeting/MeetingTest.java
backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java

- resolves: #51 
약속을 생성하는 기능을 구현합니다.
로직은 아래와 같은 순서로 동작합니다.
* 주최자를 참여자로 등록(회원가입)합니다.
* 약속 허용날짜(avilableDates)를 저장합니다.
* 약속(Meeting)을 저장합니다.
요청
```http
POST /api/v1/meeting HTTP/1.1
{
"hostName": "momo_host",
"hostPassword": "momo_password",
"meetingName": "momo_meeting",
"meetingAvailableDates": [
"2024-07-20",
"2024-07-21",
"2024-07-22"
],
"meetingStartTime": "8:00",
"meetingEndTime": "22:00"
}
```
응답
```http
HTTP/1.1 201 Created
Location: /meeting/{uuid}
```
1. PRG(Post-Redirect-Get)의 필요성
구현한 약속 생성 API는 아래와 같은 로직입니다.
>     (1) 약속 생성 등록 페이지에서 등록 버튼을 누르면 POST 요청
>     (2) 정보 페이지로 이동하면서 응답받은 값을 정보 페이지에 뿌려줌
그러나 이렇게 구현하면 사용자가 새로고침을 할 경우 POST 재요청되고, 또 다른 Meeting이 생성될 것으로 예상됩니다.
만약 예상한 대로 동작한다면, 리다이렉트하여 새로고침 시 GET 요청이 가도록 수정할 예정입니다.
2. UUID 라이브러리
UUID 버전은 사전에 논의한 내용과 아래 자료를 참고하여 v4로 선택했습니다. …

[BE] 약속 생성 API 구현

---

frontend/src/components/_common/Field/Field.stories.tsx
frontend/src/components/_common/Field/Field.styles.ts
frontend/src/components/_common/Field/index.tsx
frontend/src/components/_common/Input/Input.stories.tsx
frontend/src/components/_common/Input/Input.styles.ts
frontend/src/components/_common/Input/index.tsx
frontend/src/hooks/useInput/useInput.ts

- resolves: #61 
- Input
- Input 컴포넌트 구현
- Input 스토리북 작성
- Field 
- Field 컴포넌트 구현
- Field 스토리북 작성
- useInput hook 구현
스토리북에서 한국어로 작성된 예제들을 포함하였으며, 각 컴포넌트의 다양한 상태를 확인할 수 있습니다.

[FE] Input, Field 컴포넌트 구현

---

.github/workflows/backend-cd.yml
.gitmodules
backend/Dockerfile
backend/build.gradle

- resolves #59
- resolves #65 
백엔드 기능 구현 후 `develop` 브랜치에 머지되었을 때 배포 자동화 환경을 구축했습니다.
#59 에서 언급했던 것 처럼 현재는 개발서버에 대한 CD에 가까운데요, 이후 릴리즈 브랜치가 생기면 프로덕션 배포 자동화도 별개로 추가해야 할 듯 합니다!
`develop` 브랜치의 `/backend` 경로 하위에 변경사항이 발생할 경우 다음과 같은 순서로 배포를 진행합니다.
1. `bootJar` 빌드
2. `jar`을 포함한 Docker 이미지 빌드 후 Docker Hub 업로드
3. EC2 인스턴스에서 Docker 이미지 pull -> 컨테이너 실행
* 3번 작업은 EC2 인바운드 제한 정책을 준수하기 위해 self-hosted runner에서 동작합니다.
`application.yml` 과 같은 중요 프로퍼티를 외부에 공개하지 않기 위해 `git submodule` 을 사용합니다.
비공개 레포지토리는 [`/2024-momo-config`](https://github.com/woowacourse-teams/2024-momo-config)이며, **변경사항 발생 시 `pull` 해야 하므로 프론트 크루분들도 함께 콜라보레이터로 초대해 두었습니다.**
레포지토리 내 서브모듈의 경로는 다음과 같습니다.
```text
/backend/src/main/resources/security
```
본 PR 병합 이후 `develop`에서 분기하는 브랜치의 `application.yml`은 서브모듈 내의 `yml` 파일로 관리해야 합니다.
서브모듈 내의 프로퍼티들을 …

[BE] 백엔드 CD 자동화 환경 구축

---

frontend/src/components/_common/Dropdown/Dropdown.stories.tsx
frontend/src/components/_common/Dropdown/Dropdown.styles.ts
frontend/src/components/_common/Dropdown/index.tsx
frontend/src/hooks/useTimeRangeDropdown/constants.ts
frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.ts
frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts

- resolves: #70 
- 드롭다운 컴포넌트 구현
- 시간 선택 hook 구현
- 시간 선택 시, startTime이 endTime을 느리거나 endTime이 startTime보다 빠르면 선택되지 않도록 구현
- 시간 선택 hook이 정상적으로 동작하는지 테스트케이스 작성
- 시간 선택 시, startTime이 endTime을 느리거나 endTime이 startTime보다 빠르면 선택되지 않도록 구현
이 부분은 추후에 변경사항이 생길 수도 있지만 일단은 구현해두었습니다!

[FE] Dropdown 컴포넌트 제작 및 시간 선택 hook 구현

---

backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeRepository.java
backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingResponse.java
backend/src/test/java/com/woowacourse/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java

- resolves: #80 
- 기존에 존재하는 약속 정보 조회 API 응답에 참가자들의 이름 리스트를 추가하였습니다.

[BE] 기존 약속 정보 조회 API 응답에 참가자들의 정보 추가

---

.github/workflows/frontend-ci.yml
frontend/jest.config.js

[FE] CI 설정 파일에서 report 경로를 수정합니다.

---

backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleDateTimesResponse.java

- resolves: #84 
- `ScheduleDateTimesResponse`의 시간 필드 앞 `@JsonFormat(shape = Shape.STRING, pattern = "HH:mm", timezone = "Asia/Seoul")` 어노테이션을 추가하였습니다.

[BE] 참가자 스케줄 조회 반환 값 내 시간 포멧팅 수정

---

backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java

- resolves: #83 
약속을 생성할 때, 약속의 uuid를 응답 바디에 넣어 보냅니다.

[BE] 약속 생성 API에서 바디를 통해 uuid를 제공

---

backend/build.gradle
backend/src/main/java/com/woowacourse/momo/config/swagger/SwaggerConfig.java

- resolves: #89 
Swagger UI를 적용했습니다.
API인증에 사용될 Bearer 토큰을 설정하는 버튼을 생성하기 위한 설정을 제외한 추가적인 설정은 아직 하지 않았습니다.
`GET /api/docs` 로 접속하면 Swagger UI를 확인할 수 있습니다.
`application.yml`에 설정이 추가되면서 submodule에 변경사항이 생겼습니다.
서브모듈 업데이트 하세요~

[BE] Swagger UI 임시 적용

---

backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java

- resolves: #97 
- JWT 토큰을 검증하고 식별된 사용자로 자신의 스케줄을 조회하는 기능을 추가하였습니다.

[BE] JWT 토큰을 통해 자신의 스케줄을 조회할 수 있는 기능 추가

---

backend/src/main/java/com/woowacourse/momo/config/swagger/SwaggerConfig.java

- resolves: #110 
리버스 프록시 뒤에서 동작하는 Swagger에서 https 스키마를 자동 인식하지 못하는 문제를 해결했습니다.
자세한 내용은 이슈를 참조해 주세요!
`SwaggerConfig.apiVersion` 은 아직 불필요하다고 생각해서 제거했습니다.
제거하면서 서브모듈에 저장된 `yaml` 프로퍼티 파일에도 변경사항이 있어요!

[BE] fix(SwaggerConfig): ForwardedHeaderFilter 추가

---

backend/src/main/java/com/woowacourse/momo/controller/attendee/AttendeeController.java
backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
backend/src/test/java/com/woowacourse/momo/controller/attendee/AttendeeControllerTest.java
backend/src/test/java/com/woowacourse/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java

- resolves: #104 
RESTful API 디자인 원칙에 기반하여 현재 구현되어 있는 API Path를 개선하였습니다.
| 기능                           | HTTP 메서드 | URI 경로                                   |
| ------------------------------ | ----------- | ------------------------------------------ |
| 참가자 로그인                  | POST        | /api/v1/meetings/{uuid}/login            |
| 약속 정보 생성                 | POST        | /api/v1/meetings                         |
| 약속 정보 조회                 | GET         | /api/v1/meetings/{uuid}                  |
| 약속 공유 조회                 | GET         | /api/v1/meetings/{uuid}/sharing          |
| 일정 생성                      | POST        | /api/v1/meetings/{uuid}/schedules        |
| 약속의 모든 일정 조회          | GET         | /api/v1/meetings/{uuid}/schedules        |
| 약속의 특정 회원 일정 조회     | GET …

[ALL] RESTful API 디자인 원칙에 기반하여 기존 API path를 수정

---

frontend/src/apis/getHeaders.ts
frontend/src/apis/getMeetingFrame.ts
frontend/src/apis/postSchedule.ts
frontend/src/components/Time/Picker/TimePickerContainer.tsx
frontend/src/components/Time/Viewer/index.tsx
frontend/src/constants/cookies.ts
frontend/src/constants/queryKeys.ts
frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.styles.ts
frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
frontend/src/router.tsx
frontend/src/stores/servers/schedule/mutations.ts

- resolves: #101 
- 링크 공유, 로그인 페이지에 대한 라우팅 경로를 정의하고,해당 컴포넌트를 연결
- 라우팅 경로명 재설정 필요 (합치는 과정에서 임의로 설정하였습니다. 추후 리팩터링 시 더 적합한 path명으로 변경해봅시다!)

[FE] 비회원 로그인 페이지와 약속 조회/수정 페이지를 연결

---

.github/workflows/discord-issue.yml
.github/workflows/discord-pull-request.yml
.github/workflows/discord-review.yml

- resolves: #121 
- 작업 현황 디스코드 알림 yml 파일을 개선했어요!
- 머지 메시지 구조 수정
- changes_requested, comment에만 알림이 가도록 변경
- single comment에는 알림이 가지 않도록 변경
빠른 머지 제발.

[ALL] 작업 현황 디스코드 알림 yml 파일 개선

---

backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
backend/src/main/java/kr/momo/domain/attendee/Attendee.java
backend/src/main/java/kr/momo/domain/attendee/Role.java
backend/src/main/java/kr/momo/domain/meeting/Meeting.java
backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/domain/attendee/RoleTest.java
backend/src/test/java/kr/momo/domain/meeting/MeetingTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java

- resolves: #112 
- 약속 필드 내 `boolean` 타입의 잠금 여부를 추가하였습니다.
- 기존 스케줄 생성시 약속이 잠금일 경우 예외가 발생하도록 검증을 추가하였습니다.
- 해당 PR이 머지되면 잠금 취소 기능도 추가할 예정입니다.
> 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?
`Meeting` 객체 내 중복된 잠금 시도시 예외가 발생하도록 로직이 짜여져있는데요.
불필요한 검증일지 궁금합니다!

[BE] 약속 잠금 API 추가

---

backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
backend/src/main/java/kr/momo/domain/meeting/Meeting.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java

- resolves: #120 
- 약속 잠금 해제 기능을 구현하였어요 :)

[BE] 약속 잠금 해제 기능 추가

---

backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
backend/src/main/java/kr/momo/service/attendee/dto/TokenResponse.java
backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
backend/src/test/java/kr/momo/service/auth/JwtManagerTest.java

- resolves: #117 
- 응답 시 ResponseBody, 요청 시 Authorization 헤더에 jwt 토큰을 저장하던 방식을 쿠키로 변경하였습니다.
- 쿠키의 `HttpOnly`, `Secure` 옵션을 활성화 하였습니다.
- 요청시 현재 사용자가 접속한 UUID와 일치하는 인증 쿠키만 전송하도록 인증 쿠키 path에 약속 UUID를 포함하였습니다.

[BE] 기존 jwt 토큰 응답 방식을 쿠키로 변경하고 path 및 보안 설정

---

.github/workflows/backend-cd.yml
.gitignore
backend/Dockerfile
backend/build.gradle
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-local.yml
backend/src/main/resources/application.yml
backend/src/main/resources/datasource.yml
backend/src/test/resources/application.yml

- resolves: #134 
현재 배포된 서버는 개발용 서버의 느낌이 강하므로 AWS상에서 DB용 인스턴스를 추가하고 서브넷을 구성하는 대신, 제 개인 서버에 구축해 둔 MySQL 서버에 연결해 두었습니다.
(외부 접속이 비허용된 AWS의 인바운드 정책을 저희가 수정할 수 없으므로, 개발용 DB 서버를 AWS상에서 구축할 경우 불편할 것으로 판단했어요🙂)
이후 전체적인 기능이 완성되고 스키마가 확정됐을 때 AWS상에서 Private Subnet을 만들어 DB 서버를 해당 서브넷 안에 구축하면 될 것 같습니다.
환경을 쉽게 관리하기 위해 프로필을 분리했습니다.
| 프로파일 | DB | JWT Secret | `hibernate.ddl-auto` |
|--------|--------|--------|--------|
| `local` | In-Memory H2 | 랜덤 값 | create |
| `dev` | MySQL 테스트 서버 | 개발서버용 시크릿 | update |
| `local` + `local-remoteDB` | MySQL 테스트 서버 | 랜덤 값 | update | 
```yml
spring:
config.import: optional:classpath:property-override.yml  # (*1)
profiles:
active: local  # (*2)
group:
local: local  # (*3)
dev: dev
```
- *1) 로컬 개발 환경에서 프로퍼티를 쉽게 오버라이드하기 위한 옵션입니다.
- `/src/main/resource/property-override.yml` …

[BE] SpringBoot 프로퍼티 분리, MySQL Server 연결

---

frontend/src/components/_common/Button/Button.styles.ts
frontend/src/components/_common/Calendar/Calendar.styles.ts
frontend/src/components/_common/TimeSlot/TimeSlot.styles.ts
frontend/src/pages/CreateMeetingPage/CreateMeetingPage.styles.ts
frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
frontend/src/styles/theme.ts
frontend/src/styles/tokens/colors.ts
frontend/src/styles/tokens/typography.ts
frontend/src/types/styles/theme.d.ts

- resolves: #124 
- colors
- typography
- 피그마에 있는 값들은 모바일 규격과 맞지 않다고 판단했어요.
- 그래서 `title`의 `font-size`를 `2.4rem`으로 잡고, title -> subtitle -> body -> caption 순으로 `0.4rem` 씩 내리면서 스타일을 설정했습니다.
- font-size, font-weight, line-height를 함께 설정했어요
- timetable
- 선택된 색상과, 선택되지 않은 색상을 구분하기 위해서 `selected`, `unselected` 프로퍼티를 추가하여 구분했어요.
- `unselected` 같은 경우 피그마 디자인과 약간 색이 달라요. 
- `dark` 색상은 사용자가 시간을 수정할 때, 선택한 시간과 더 대비되도록 하기 위해서 어둡게 할 때 사용하면 될 것 같아요
- 변경된 `grey` 팔레트 색상 피그마에 적용 예정
- 변경된 `typography` 피그마에 적용 예정
- red 색상에 관해서 추가 논의 필요

[FE] colors, typography 디자인 토큰 생성

---

backend/src/main/java/kr/momo/domain/availabledate/AvailableDateRepository.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java

- resolves: #148 
미팅 정보 응답 시 날짜를 정렬해서 응답합니다.
없음

[BE] 미팅 조회 시 날짜 정보를 정렬하여 반환하도록 수정

---

backend/src/main/java/kr/momo/config/TimeConfig.java
backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
backend/src/main/java/kr/momo/domain/availabledate/AvailableDate.java
backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/domain/availabledate/AvailableDateTest.java
backend/src/test/java/kr/momo/domain/availabledate/AvailableDatesTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java

- resolves: #135 
- 약속 생성시 과거 날짜가 포함되어 있다면 예외가 발생하도록 검증을 추가하였습니다.
- 관련한 테스트도 추가하였어요.
>  추가 검토 사항: 코드, 디자인, 구현 방식 등에 대한 추가적인 검토가 필요한 사항이 있나요?
현재 날짜(`LocalDate`) 객체 생성이 적절한 계층에 수행되고 있는지 궁금합니다. 과거 시간 검증은 API가 요청된 시점의 오늘을 기준으로 이전 날짜인지 검증하게 되는데요.  이때 비즈니스 로직에 대한 테스트를 위해 Persistence Layer(`MeetingController`)에 위치하고 있습니다. 이것이 적절한지 궁금합니다.
> 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?
과거 시간 검증에 대한 인수 테스트(`ControllerTest`)가 필요한지 궁금합니다. 현재 테스트 내 400 Bad Request 상황에 올바른 상태코드를 반환하는 테스트가 이미 있는데요. 과거 검증 인수테스트를 추가한다면 문맥은 다르나 테스트하고자 하는 목적이 `400 Bad Request` 반환으로 동일할 것 같다 생각하기 때문입니다. 여러분의 의견이 궁금하네요. 필요하다면 바로 반영하겠습니다.

[BE] 약속 생성시 과거 날짜 검증 추가

---

backend/src/main/java/kr/momo/controller/CookieManager.java
backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
backend/src/main/resources/application-local.yml
backend/src/test/resources/application.yml

- resolves: #162 
JWT 저장용 쿠키 응답 시 도메인을 설정하고, 올바를 Path 정보를 응답하도록 수정했습니다.
서브모듈이 업데이트되었습니다.
`CorsConfig`의 `.allowedOriginPatterns()` 이 제대로 동작하지 않는 오류가 있습니다.
`String[]` 을 문자열로 만들지 않고 그대로 전달하는 것으로 변경해야 정상 동작합니다.
이후 다른 이슈를 만들어 수정하겠습니다!

[BE] JWT 쿠키의 경로와 도메인 값 지정

---

.github/workflows/backend-cd.yml

- resolves: #173 
- `backend-cd.yml` 중 docker 실행 라인 내 volume 설정 추가했습니다.
- 로그를 ec2 내부에 써내려야하기에 `ro`설정을 하지 않았습니다.
- `$HOME`이 어떤 걸 뜻하는지 명확히 알지 못하여 ec2의 루트임을 예상하여 다음과 같이 설정하였습니다.
리뷰 중점 사항: 리뷰어가 특히 집중해서 봐야 할 부분이 있나요?
- docker에 관한 지식이 부족하여 관련 설정이 유효할지 궁금합니다!

[BE] 컨테이너에 로그 폴더 마운트 볼륨 추가

---

frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts

[FE] 시간 선택 옵션 수정

---

frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/index.tsx
frontend/webpack.common.js

- resolves: #168 
- 배포 환경에서 장애가 발생했을 때, 데이터를 수집하기 위해 사용할 Sentry 기본 환경을 구축했어요.
- 디스코드 알람과 연동해서, 디스코드 모모 서버 🚨프론트엔드-에러로깅🚨 채널에 알람이 올 수 있도록 했어요.
- **주의사항**
- 어떤 파일의 어떤 줄(L)에서 예외가 발생했는지 확인하기 위해서, source-map을 활용합니다. 
- 항상 배포 환경에서 사용하는 번들 js 파일을 난독화하는 source-map과 sentry에서 에러 트래킹에 사용하는 source-map이 싱크가 맞아야하는 것을 주의해야 합니다.
- 그래서 앞으로 배포할 때 CD를 적용한다면, 해당 yml 파일에서 새롭게 번들링된 js 파일에 대한 source-map을 Sentry에 올리기 위한 job을 추가해야할 것 같아요!
- 참고 : https://docs.sentry.io/platforms/javascript/sourcemaps/
- 모모 서비스를 이용하는 사용자의 행동 분석을 위한 GA 환경을 구축했어요
- index.html 파일에 `Google Analytics`에서 제공하는 스크립트 코드를 넣어서 등록했고, 최근 30분간 방문 사용자를 추적할 수 있음을 확인했습니다. 
- 앞으로 어떤 행동 지표를 중점적으로 분석할지 결정하고, 점진적으로 지표 수집을 해가야할 것 같아요!

[FE] 에러 트래킹을 위한 Sentry 환경 구축, 사용자 행동 분석을 위한 GA 환경 구축

---

backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
backend/src/main/java/kr/momo/controller/attendee/AttendeeControllerDocs.java
backend/src/main/java/kr/momo/domain/attendee/Attendee.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
backend/src/test/java/kr/momo/service/attendee/AttendeeServiceTest.java

- resolves: #182 
미팅의 모든 참여자의 이름을 조회하는 기능을 구현했습니다.
API 형식
요청
```http
GET /api/v1/meetings/{uuid}/attendees
```
응답
```http
{
"data" : ["daon", "mark"]
}
```
(1) 미팅의 uuid를 제공하면 uuid에 해당하는 미팅을 조회한 후, 해당 미팅의 모든 참여자의 이름을 반환하는 기능입니다. 이 기능에 대해서 로그인이 필요할지 의문입니다. (현재는 로그인하지 않습니다.)
(2) 컨트롤러와 서비스의 함수 명이 애매합니다. 혹시 괜찮은 메서드명 있다면 추천 부탁드립니다.

[BE] 미팅에 속하는 모든 참여자의 이름을 조회하는 API

---

backend/src/main/java/kr/momo/controller/annotation/ApiSuccessResponse.java
backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeetingRepository.java
backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/fixture/ConfirmedMeetingFixture.java
backend/src/test/java/kr/momo/fixture/MeetingFixture.java
backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java

- resolves: #142 
주최자가 확정된 약속을 취소하는 기능을 구현했습니다. 
요청
```
DELETE /api/v1/meetings/{uuid}/confirmed HTTP/1.1
cookie: ~host-cookie~
```
응답
```
HTTP/1.1 204 No Content
```
- 확정된 약속을 취소하고 참가자들의 약속을 수정하는 경우가 많을 것이라 가정하여 **약속 잠금 해제까지 수행**합니다.
-  아직 확정 약속 조회 기능이 구현되지 않아 컨트롤러 테스트에서 repo를 통해 검증하는데 기능이 구현된다면 RestAssured로 검증할 예정입니다.
- 약속 확정의 경우 `POST **/confirm` 취소와 조회의 경우 `GET or DELETE **/confirmed` 엔드포인트를 사용할 예정입니다. 헷갈릴 여지를 줄이기 위해 `/confirm` 경로를 사용하는 것이 나을지 의견이 궁금합니다.
- 확정된 약속이 존재하지 않더라고 삭제 요청 시 204 상태 코드를 응답합니다. 해당 상황으로 인해 클라이언트에서 문제로 인식하지 않아도 괜찮다고 생각했어요.

[BE] 약속 확정 취소 기능 구현

---

backend/src/main/java/kr/momo/domain/attendee/Attendee.java
backend/src/main/java/kr/momo/domain/attendee/Role.java
backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
backend/src/test/java/kr/momo/domain/attendee/RoleTest.java

- resolves: #201 
기존 약속 정보 조회 API 호출 시 응답에 약속 주최자 이름을 포함하였습니다.

[BE] 약속 정보 조회시 주최자의 이름을 함께 반환

---

.github/workflows/frontend-cd.yml

- resolves: #208 
- 프론트엔드 배포를 자동화 할 수 있도록 yml 파일을 구성
- [여기](https://paper-mass-5ff.notion.site/fa9cf48f0dbd49e2bc8015af48b3fc34)(노션 백로그)서 yml 파일 구성에 대한 상세한 설명을 확인할 수 있다. 
1. **트리거 시점**
develop 브랜치에서 시작해서 
- 새로운 기능(feature)를 구현하고,
- develop 브랜치로 PR(Pull Request)를 생성하고,
- 코드 리뷰를 주고 받다가 develop 브랜치로 머지가 될 때 Frontend CD workflow를 실행한다.
깃허브 이벤트에는 merge가 존재하지 않으므로, develop 브랜치에 push가 되었을 때 워크 플로우를 실행한다.
2. **self-hosted를 사용하는 이유**
깃허브 서버에서 특정 job, run들을 수행하면 `ubuntu-latest` 환경에서 수행한다. 하지만, **깃허브 서버에서는 우아한테크코스 aws에 직접 접근할 수 없기 때문에** 우아한테크코스 aws에서 생성한 모모 EC2 인스턴스를 `self-hosted`로 사용해서 `aws cli`로 s3, cloudfront와 싱크를 맞춘다.

[ALL] 프론트엔드 배포 자동화 yml 파일 생성

---

backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java

- resolves: #215 
- 스케줄이 확정 일정 범위에 해당하는지 확인하는 메서드의 문제를 해결했습니다.
- 스케줄의 Timeslot은 확정 일정의 시작 시간에 inclusive 합니다.
- 확정 일정의 끝 시간은 TimeSlot의 개념이 아니므로 exclusive 합니다.   
=> [시작 시간, 끝 시간)
- 기존 잘못된 로직이 테스트를 통과하지 못하도록 수정했습니다.
```java
LocalDateTime dateTime = schedule.dateTime();
// 이전 코드 return !dateTime.isBefore(startDateTime) && !dateTime.isAfter(endDateTime);  [시작 시간, 끝 시간] X
return !dateTime.isBefore(startDateTime) && dateTime.isBefore(endDateTime); //  [시작 시간, 끝 시간) O
```

[BE] 확정 조회 문제 해결

---

frontend/src/hooks/useTimeRangeDropdown/constants.ts
frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
frontend/src/pages/CreateMeetingPage/index.tsx

- resolves: #216
> 노션 링크 : https://paper-mass-5ff.notion.site/endTime-76d6260270e94ee1aca5d84aa5f847ae?pvs=4
기존 로직과 이에 대한 문제점 -> 해결방안 순서대로 노션에 정리해두었습니다.
- endTime 초기값 변경
- endTime을 서버로 보낼 때 24:00라면 00:00로 보내도록 설정

[FE] 약속 시간 선택 default endTime 수정

---

frontend/src/styles/tokens/colors.ts

#FFBABC -> #FF8DA6
- resolves: #220 
300: `#FFBABC`
500: `#FF8DA6`
기존에 선택한 primary color의 색상이 500번의 색상이였으며, 색상이 연하다는 사용자 피드백이 있었습니다.
<figure class="half">
<figurecaption>좌: 기존 색상, 우: 변경된 색상</figurecaption>
</figure>

[FE] primary color 수정

---

backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
backend/src/main/java/kr/momo/domain/meeting/Meeting.java
backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/main/java/kr/momo/service/meeting/dto/MeetingCreateResponse.java
backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/domain/meeting/MeetingTest.java
backend/src/test/java/kr/momo/domain/timeslot/TimeslotTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java

- resolves: #225 
약속 생성 완료 시 생성된 약속에 대한 정보들을 응답합니다.
약속 생성 완료 화면에서 사용자의 입력이 제대로 저장되었다는 UI를 표시하기 위해 사용합니다.
- `Timeslot` 에 각 슬롯의 시작 시각과 끝 시각을 반환하는 메서드를 추가했습니다.
- 메서드의 의미를 반영하여 `Meeting`의 `startTimeSlotTime()` 과 `endTimeSlotTime()` 이 각각 `earliestTime()`, `lastTime()` 으로 변경되었습니다.
- `Timeslot`의 `localTime` 필드는 해당 슬롯의 '대푯값' 으로만 사용됩니다. 의미 있는 값을 참조하기 위해서는 `Timeslot.startTime()` 과 `Timeslot.endTime()` 으로 참조해 주세요
**현재 DTO 응답 시 날짜 정보를 정렬해서 응답하지 않습니다.** `TreeSet` 으로 일괄 변경하면 좋을 것 같은데, 다른 브랜치에서 작업하는게 좋을 것 같아 다음 이슈 파서 작업할게요~
cc. @Largopie

[BE] 약속 생성 완료 시 생성된 약속의 정보를 응답

---

backend/src/main/java/kr/momo/domain/schedule/ScheduleRepository.java

- resolves: #210 
API 호출 시 쿼리가 N+1 번 호출되는 문제를 확인하고 이를 Fetch Join으로 해결하였습니다.
N+1 문제가 발생하는 API는 다음과 같습니다.
**약속 추천 기능은 현재 고려대상에서 제외하였습니다.**
- ScheduleService
- findAllSchedules
- findSingleSchedule
- findMySchedule
위 메서드 모두 ScheduleRepository를 통해 List<Schedule>을 조회하여 Dto로 변환하는 과정에서 문제가 발생합니다.
`List<Schedule>`를 조회하기 위해 SQL을 1번, Schedule의 `AvailableDate`를 참조할 때 마다 SQL이 호출되어 N+1입니다.
ScheduleRepository의 `findAllByAttendee()`, `findAllByAttendeeIn()` 메서드에 `@EntityGraph`를 사용해서 항상 `AvailableDate`를 함께 조회할 수 있도록 하였습니다.
`findAllByAttendeeIn()` 같은 경우 현재 약속 추천 기능에도 사용되고 있지만
약속 추천 기능이 현재 완전하지 않으므로 `findAllByAttendeeIn()`를 별도의 fetch join 메서드로 분리하지는 않았습니다.
`JOIN FETCH`와 `@EntityGrpah`의 차이는 각각 inner join과 left outer join으로 동작하는 차이이며
직접 JPQL로 JOIN FETCH를 사용하여 해결해도 되지만, 간단한 EntityGrpah 어노테이션으로 문제를 해결하였습니다.

[BE] N+1 Query 문제를 해결

---

.github/workflows/frontend-cd.yml

- resolves: #239
프론트엔드 CD 워크플로우의 self hosted runner 지정 구문에서 러너를 고유하게 식별할 수 있도록 다음과 같은 태그를 추가했습니다.
- self-hosted
- linux
- ARM64
- dev
핫픽스 브랜치라 빠른 머지 부탁드려요~

[FE] CD 워크플로우에서 Self hosted runner 상세 태그 지정

---

backend/src/main/java/kr/momo/domain/availabledate/AvailableDateRepository.java
backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
backend/src/main/java/kr/momo/domain/schedule/Schedule.java
backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
backend/src/test/java/kr/momo/domain/availabledate/AvailableDatesTest.java
backend/src/test/java/kr/momo/domain/meeting/MeetingTest.java
backend/src/test/java/kr/momo/domain/timeslot/TimeslotIntervalTest.java
backend/src/test/java/kr/momo/domain/timeslot/TimeslotTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java

- resolves: #230 
`AvailableDate` 의 일급 컬렉션인 `AvailableDates` 가 내부 필드로 `List` 가 아닌 `SortedSet`을 가지고 있도록 변경했습니다.
그에 따라 리스트에서 `O(N)` 으로 동작하던 몇 연산들을 `O(1)` 혹은 `O(log N)`로 수행할 수 있도록 최적화했습니다.
자료구조 특성상 더 이상 중복된 값이 존재할 수 없으므로 중복 검증 로직과 테스트를 삭제했습니다.
`AvailableDates`는 도메인이죠. 현재 흐름대로 사용한다면 (테스트코드를 제외하고는) 모두 같은 `Meeting`에 대한 `AvailableDate`들을 래핑하고 있어요.
이때, 생성자로 전달되는 각 `AvailableDate` 들이 같은 `Meeting`을 가지는지를 검증해야 할까요?
로직상에서 강제로 `Meeting`이 다른 `AvailableDate`를 리스트에 담고, 그 리스트를 기반으로 `AvailableDates`를 생성하지 않는 이상 서로 다른 Meeting을 가질 일이 전혀 없긴 해요.
개인적으로는 `AvailableDates`라는 객체를 같은 `Meeting`에 대한 `AvailableDate`의 컬렉션으로 정의했기 때문에, 강제 생성 케이스를 제외하고는 만들어질 일이 없다고 하더라도 검증을 추가하는게 좀 더 견고한 도메인이 될 수 있는 방향이라고 생각합니다.
하지만 검증 로직을 작성 중, 다음과 같은 의문이 남아 우선 검증을 추가하지 않은 상태입니다.
1. 현재 `List.of(new AvailableDates(new Meeting(..)..))` 과 같이 …

[BE] AvailableDates가 내부적으로 정렬된 상태를 유지하도록 개선

---

frontend/src/apis/meetings.ts
frontend/src/apis/schedules.ts
frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
frontend/src/components/AttendeeTooltip/index.tsx
frontend/src/components/MeetingTimeCard/MeetingTimeCard.styles.ts
frontend/src/components/Schedules/AllSchedule.tsx
frontend/src/components/Schedules/Picker/SchedulePicker.utils.ts
frontend/src/components/Schedules/Picker/SchedulePickerContainer.tsx
frontend/src/components/Schedules/Picker/index.tsx
frontend/src/components/Schedules/SchedulesViewer.tsx
frontend/src/components/Schedules/SingleSchedule.tsx
frontend/src/layouts/GlobalLayout.styles.ts
frontend/src/stores/servers/meeting/mutation.ts
frontend/src/types/meeting.ts
frontend/src/types/schedule.ts

- resolves: #244 
- 00:00~01:00 시간 범위로 약속을 생성할 경우, 02:00까지 렌더링되는 문제 해결했습니다.
```
{
"data": {
"meetingName": "momo",
"firstTime": "00:00",
"lastTime": "01:00",
"isLocked": false,
"availableDates": ["2024-07-24", "2024-07-25", "2024-07-26", "2024-07-27"],
"attendeeNames": ["낙타", "해리", "빙봉"]
}
}
```
다음과 같이 00:00-01:00으로 약속을 생성하는 경우에는 
01:00까지만 렌더링 되도록 문제를 해결했습니다. 
```ts
const generateTimeSlots = (start: string, end: string) => {
const startHour = Number(start.split(':')[0]);
const endHour = Number(end.split(':')[0]);
const slots: string[] = [];
for (let i = startHour; i <= endHour; i++) {
slots.push(`${i.toString().padStart(2, '0')}:00`);
}
return slots;
};
```
알고 보니까, endHour까지 포함해서 약속을 생성했기 때문에 생기는 문제였어요 :)
유틸 함수와 컴포넌트에서 반복해서 사용되는 타입들이 @api 폴더에서 관리되고 있는데 여기저기서 사용되는 타입들은 @types 폴더에서 관리되는게 …

[FE] 00:00~01:00 시간 범위로 약속을 생성할 경우, 02:00까지 렌더링되는 문제 해결

---

backend/src/main/resources/application-api-docs.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

- resolves: #235 
운영 환경이 추가되어 관련된 yml 파일과 몇가시 수정사항을 반영하였습니다. 
먼저, 서브모듈에 DB 관련 대외비를 추가하였습니다!
다음으로 운영 환경에 jpa 관련 동작을 명시하였습니다. 운영 환경에서 sql을 출력할 필요가 없어 관련 설정을 삭제하였습니다.
마지막으로 Swagger를 운영 환경 내 있을 필요가 없기에 관련 설정을 비활성화하였습니다!
> 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?
운영환경에서 swagger 관련 설정들을 비활성화하면서 `SwaggerConfig`이 운영 환경에서는 불필요한데요.
해당 Config 클래스를 `@Profile`을 이용하여 운영 환경 적용시 해당 빈들을 추가하지 않게끔 설정해야할지 고민입니다!

[BE] 운영환경 yml 추가

---

frontend/src/components/Schedules/SchedulesViewer.tsx
frontend/webpack.common.js

- resolves: #258 
> 모듈을 import 또는 require 할 필요 없이 자동으로 로드합니다.
해당 속성에 의해서 "tsx 파일이 아님에도 불필요하게 React를 import하는 문제가 발생하지 않을까?"라는 생각이 들어서 babel에 관련된 여러 정보도 추가적으로 찾아봤는데 마땅한 해답을 찾지 못했습니다. 그래도 일단은 동작하게 하는 것이 중요하기 때문에 이와 같이 적용하게 되었습니다.

[FE] ProvidePlugin 설정

---

frontend/src/components/PasswordInput/index.tsx
frontend/src/components/_common/Field/Field.styles.ts
frontend/src/components/_common/Input/Input.styles.ts
frontend/src/pages/CreateMeetingPage/index.tsx

- resolves: #263 
SVG 컴포넌트에 width와 height 값이 설정되지 않아 발생한 문제입니다. → width와 height를 각각 20으로 설정하였습니다.
`PRIMITIVE_COLORS.red`가 기존의 단일 값(`red: '#ff0000'`)에서
다중 값(`red: { 100: '#F58E8E', 200: '#F26969', 300: '#EF4545', 400: '#EB1E1E', 500: '#CE1212' }`)으로 변경되었습니다.
이에 따라 기존 코드에서 `PRIMITIVE_COLORS.red`를 참조하면 `undefined`가 반환되어 검은색으로 표시되는 문제가 발생했습니다. → 오류 메시지 색상을 빨간색(`PRIMITIVE_COLORS.red[300]`)으로 수정하였습니다.
iOS/사파리에서는 `input` 및 `textarea` 요소의 `font-size`가 16px 미만일 경우 포커스 시 자동으로 화면이 확대되는 특성이 있습니다.
이를 방지하기 위해 `input` 스타일에 16px 이상의 `bodyLight` 타이포그래피를 적용하였습니다.
약속 이름과 비밀번호 입력 필드의 자동완성을 방지하였습니다.
약속 이름 필드에는 `autoComplete="off"` 속성을 적용하였으며, 비밀번호 필드(input type="password")의 경우 `autoComplete="off"`가 동작하지 않기 때문에 `autoComplete="new-password"` 속성을 적용하였습니다.
닉네임 필드의 경우, 사용자들이 자주 사용하는 닉네임을 자동완성으로 편리하게 입력할 수 있도록 …

[FE] 입력 필드 버그 수정

---

frontend/src/components/Schedules/SchedulePicker/index.tsx
frontend/src/components/Schedules/Schedules.util.ts
frontend/src/hooks/usePagedTimePick/usePagedTimePick.ts
frontend/src/hooks/useTimePick/useTimePick.ts

- resolves: #269 
약속 시간을 설정할 때, 되는/안되는 시간을 구분해서 설정할 수 있는 기능을 추가했습니다.
1. `되는 / 안되는`을 구분할 수 있는 클라이언트 상태를 추가한다.
2. 되는 / 안되는 상태에 따라서 사용자가 테이블을 드래그할 때 강조되는 색을 변경한다.
(안되는 시간을 선택할 경우 어떤 색을 사용해서 구분할지는 확실하게 정해지지 않아서 일단 같은 색을 사용한 후 PR 날립니다.)  
3. 되는 / 안되는 상태에 맞춰 서버에 전달해줘야 하는 데이터를 생성한다.  
4. 기존에 되는 / 안되는 상태로 선택한 시간들이 있는 경우에 선택 모드를 변경할 경우 기존에 선택한 시간은 자동으로 초기화 될 수 있도록 한다  
**->** 모달 UI가 만들어지면 모달을 사용해서 초기화가 될 수 있는데도 선택 모드를 변경하겠냐는 질문을 한 후, 초기화 할 수 있도록 한다
(아직 모달은 구현되지 않았기 때문에 레벨 4에서 추가적으로 구현하면 사용하게 될 것 같아요.)
`generateAvailableSchedules`, `generateUnavailableSchedules` 함수는 한 글자 차이 밖에 나지 않습니다.
```
if (row[colIndex])
if (!row[colIndex])
```
그럼에도 불구하고 두 개의 함수로 구분한 이유는, 
```ts
return availableDates
.map((date, colIndex) => {
const times: string[] = [];
selectedScheduleTable.forEach((row, rowIndex) => {
// …
```

[FE] 약속 시간을 설정할 때 되는/안되는 시간을 구분해서 설정할 수 있도록 기능 추가

---

frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
frontend/src/stores/servers/meeting/queries.ts

- resolves: #283 
로그아웃 후 새로운 유저로 로그인을 한 후, 시간을 등록하려는 경우 이전 유저의 시간이 남아있던 문제를 해결했습니다.
쿼리키와 관련된 캐싱 문제였습니다.  
```ts
export const useGetMyScheduleQuery = (uuid: string) =>
useQuery({
queryKey: [QUERY_KEY.meetingMySchedule],
queryFn: () => getMeetingMySchedule(uuid),
staleTime: 0,
});
```  
기존에는 위와 같이 본인의 시간을 가져오는 `useQuery`훅의 쿼리키가 상수 하나로만 설정되어 있었는데, 현재 로그인한 사용자의 닉네임을 쿼리키로 같이 저장해주는 방식으로 문제를 해결했습니다. 즉,
```ts
export const useGetMyScheduleQuery = (uuid: string, userName: string) =>
useQuery({
queryKey: [QUERY_KEY.meetingMySchedule, { userName }],
queryFn: () => getMeetingMySchedule(uuid),
staleTime: 0,
});
```
위 코드처럼 `useName`을 인자로 받아서 쿼리키에 추가해주는 방식으로 구현했습니다.

[FE] 로그아웃 후 새로운 유저로 로그인을 한 후, 시간을 등록하려는 경우 이전 유저의 시간이 남아있던 문제 해결

---

backend/build.gradle
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-local.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

- resolves: #248 
- JVM, Connection Pool 등 서비스의 지표를 얻기 위해서는 `spring actuator`의 의존성이 필요합니다.
- grafana를 이용하여 지표를 확인하기 위해선 서비스에서 지표들을 요청하여 받아가는 `spring prometheus`가 필요합니다.
- 그렇게 때문에 관련 2가지 의존성과 `/actuator/prometheus`의 경로를 열어주었습니다.
- 🚨 해당 경로는 서비스의 민감한 정보를 담은 지표들이기 때문에 외부에서 접속할 수 없도록 추가적인 설정이 필요합니다.
`/actuator/prometheus`를 배포 환경인 dev와 prod 환경에서 탐지하지 못하도록 보안 강화를 적용하였습니다.
서브모듈이 변경되었으니 `update` 부탁드립니다~

[BE] 지표 설정 관련 설정 추가

---

backend/src/main/java/kr/momo/controller/annotation/ApiErrorResponse.java
backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
backend/src/main/java/kr/momo/service/meeting/dto/ConfirmedMeetingResponse.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java

- resolves: #280 
프론트엔드에서 '확정 취소' 버튼을 host일 경우에만 보여줘야 하는데 다음과 같은 상황이 발생하기 때문에 hostName 정보 추가 요청이 들어왔습니다.
hostName에 대한 정보를 가지고 있는 경우가 아래의 2가지 경우입니다.
1. 약속생성 시 사용자가 인풋 필드에 기입한 name (클라이언트)
2. 약속 정보 조회시 response 값
1번 or 2번으로 얻은 hostName을 확정 취소 페이지에서 쓰려면 
1. 확정 취소 페이지까지 navigate 함수로 hostName 전달 + 인자로 내려주기 or 2. 전역으로 저장
하는 복잡한 경우가 발생합니다.
- AttendeeGroup에 옵셔널로 Host인 Attendee를 반환하는 메서드를 추가했습니다.
- AttendeeErrorCode.HOST_NOT_FOUND 추가했습니다.
- 따로 hostName을 반환하는 API를 추가할지 고민이 되었으나 추가로 필요한 상황이 없고 런칭데이 까지 얼마 남지 않았기 때문에 분리하지 않았습니다. 다른 곳에서도 get hostName api가 필요하게 된다면 분리하는 것을 고려하고 있습니다.
- 약속의 모든 참여자에서 주최자가 존재하지 않는다면 서버측의 문제가 있다고 생각하여 AttendeeErrorCode.HOST_NOT_FOUND를 500번 상태 코드로 설정했습니다. 문제가 되는 부분이 있다면 리뷰 부탁 드립니다.

[BE] 확정 약속 조회 시 hostName 정보 추가

---

backend/src/main/java/kr/momo/domain/availabledate/AvailableDate.java
backend/src/main/java/kr/momo/domain/availabledate/AvailableDateBatchRepository.java
backend/src/main/java/kr/momo/domain/schedule/Schedule.java
backend/src/main/java/kr/momo/domain/schedule/ScheduleBatchRepository.java
backend/src/main/java/kr/momo/domain/schedule/ScheduleRepository.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
backend/src/test/java/kr/momo/domain/availabledate/AvailableDateBatchRepositoryTest.java
backend/src/test/java/kr/momo/domain/schedule/ScheduleBatchRepositoryTest.java
backend/src/test/java/kr/momo/domain/schedule/ScheduleRepositoryTest.java

- resolves: #256 
`saveAll()`, `deleteAll()` 호출 시 엔티티 개수만큼 쿼리가 호출되는 문제를 개선했습니다.
엔티티 수 만큼 쿼리가 호출되었던 이유는 다음과 같습니다.
`saveAll()`과 `deleteAll()` 메서드는 JPA에서 다수의 엔티티를 일괄적으로 처리할 수 있도록 제공하는 기능인데요.
`saveAll()` 내부 구현을 살펴보면 하나의 트랜잭션 안에서 엔티티 수 만큼 반복문을 돌며 `save()`를 호출합니다.
```java
@Transactional
public <S extends T> List<S> saveAll(Iterable<S> entities) {
Assert.notNull(entities, "Entities must not be null");
List<S> result = new ArrayList();
Iterator var4 = entities.iterator();
while(var4.hasNext()) {
S entity = (Object)var4.next();
result.add(this.save(entity));
}
return result;
}
```
즉 매번 새로운 트랜잭션을 생성하는 `save()`와 달리 
하나의 트랜잭션 안에서 처리한다는 차이만 존재할 뿐, 엔티티 수 만큼 쿼리가 호출되는 것에는 변함이 없습니다.
이를 해결하는 방법에는 두 가지 방법이 존재합니다.
1. Hibernate가 지원하는 `hibernate.jdbc.batch_size` 옵션을 통한 Batch Update
2. Jdbc 레벨에서 Batch Update를 …

[BE] JPA의 saveAll, deleteAll를 bulk query로 개선

---

backend/src/main/java/kr/momo/controller/CookieManager.java

- resolves: #293 
개발 편의를 위해 이전에 쿠키 헤더의 SameSite 옵션을 None으로 변경했었는데요
None으로 설정했던 코드 라인을 제거하고 보안을 강화합니다.
SameSite 옵션을 명시적으로 설정하지 않으면 브라우저의 기본 설정을 따르게 됩니다.
Internet Explorer를 제외한 대부분의 최신 브라우저는 현재 SameSite = Lax 모드를 사용하고 있습니다.

[BE] 쿠키 헤더의 SameSite 옵션을 변경

---

backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
backend/src/main/java/kr/momo/domain/meeting/Meeting.java
backend/src/main/java/kr/momo/domain/meeting/MeetingRepository.java
backend/src/main/java/kr/momo/domain/meeting/RandomUuidGenerator.java
backend/src/main/java/kr/momo/domain/meeting/UuidGenerator.java
backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
backend/src/main/java/kr/momo/service/meeting/MeetingService.java
backend/src/test/java/kr/momo/domain/meeting/fake/FakeUuidGenerator.java
backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java

- resolves: #296 
`java.util` 이 제공하는 `UUID` 클래스의 버전4 UUID 생성 방식에서 영어 대소문자, 숫자를 포함하는 8글자 랜덤 문자열 생성방식으로 변경하였습니다.
현재 사용하는 버전 4 UUID는 36자 문자열의 형태를 이루어 매우 높은 고유성을 보장하는 장점이 있습니다. 하지만 길이가 다소 길어 메모리, 테이블 저장공간, 인덱스를 관리하는 측면에서 여러가지 단점을 가지고 있다고 판단하였습니다.
길이를 8글자로 변경할 경우 약 218조 개의 고유한 문자열을 생성할 수 있고
Birthday Problem 공식에 따라 UUID 1740만개를 생성했을 때 부터 충돌 가능성이 50%인 것을 확인할 수 있습니다.

[BE] 약속의 UUID 발급 방식을 개선

---

frontend/src/components/_common/Header/index.tsx

- resolves: #316 
로그아웃 시, alert가 두번 출력되는 현상 해결
=> 원인 : user mutation 레이어 분리 시, 해당 alert를 중복해서 선언했습니다. 따라서 mutation에 있는 alert를 유지하고 Header의  alert를 제거했습니다.
- 현재 alert는 UI로직인데 서버 상태관리 로직인 useMutation의 onSuccess 내부에서 사용되고 있는데, 추후 수정이 필요합니다.

[FE] 중복 선언된 alert 제거

---

frontend/package.json
frontend/src/index.tsx

- resolves: #323 
- build:dev의 노드 환경을 production으로 수정

[FE] build:dev 스크립트에서 노드 환경을 production으로 수정

---

.github/workflows/frontend-prod-cd.yml

- resolves: #328 
기존 `frontend-prod-cd.yml` 파일에서 동작하지 않았던 `detect-change`을 동작하도록 yml 파일을 수정했습니다.

[ALL] frontend-prod-cd.yml 파일의 detect-change job 수정

---

frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts

- resolves: #337 
https://github.com/user-attachments/assets/cb3503ee-307d-43ba-9a5e-8407dc7a687f
useTimeRangeDropdown util 함수 수정
```tsx
export function addHoursToCurrentTime(currentTime: string, hours: number) {
const [currentHours, currentMinutes] = currentTime.split(':').map(Number);
return (
String(currentHours + hours).padStart(2, '0') + ':' + String(currentMinutes).padStart(2, '0')
);
}
```
해당 함수가 시간, 분을 반환할 때 숫자로 반환하기 때문에 한자리 숫자일 때 앞에 ‘0’을 붙이도록 수정했습니다.
이에 대한 테스트 케이스도 추가했어용

[FE] 시간 선택 Dropdown value 수정

---

frontend/src/constants/inputFields.ts
frontend/src/hooks/useInput/useInput.ts
frontend/src/pages/AttendeeLoginPage/index.tsx
frontend/src/pages/CreateMeetingPage/index.tsx

- resolves: #339 
- 각 필드(meetingName, nickname, password)의 유효성 검사 규칙을 정규표현식으로 단순화
- 비밀번호 규칙을 4자리 숫자로 변경
- 새로운 비밀번호 규칙(4자리 숫자)에 맞게 label 텍스트 수정
- input type="number" 적용
- iOS에서는 추가 속성 적용 (`inputMode="numeric"`과 `pattern="[0-9]*"` 속성을 추가하여 iOS 기기에서 숫자 전용 키패드가 표시되도록 개선)
[작업 현황 정리 노션 링크](https://paper-mass-5ff.notion.site/4f4d0d9cfde84d0cb17f2537b7815069?pvs=4)
비밀번호 입력이 4자리 숫자로 변경되고 모바일 키패드 입력이 도입됨에 따라 `PasswordInput 컴포넌트`(비밀번호 숨기기/표시 기능이 포함된 컴포넌트)는 현재 사용되지 않고 있습니다. 
그러나 추후에 필요할 수 있으므로 컴포넌트는 삭제하지 않고 남겨두었습니다.

[FE] 비밀번호 입력 간소화 및 모바일 숫자 키패드를 적용

---

backend/src/main/java/kr/momo/domain/attendee/AttendeePassword.java
backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
backend/src/main/java/kr/momo/service/attendee/dto/AttendeeLoginRequest.java
backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
backend/src/test/java/kr/momo/domain/attendee/AttendeePasswordTest.java
backend/src/test/java/kr/momo/fixture/AttendeeFixture.java

- resolves: #341 
비밀번호 검증 로직을 `특수번호를 포함한 10자리 문자,숫자` -> `4자리 숫자`로 변경했습니다.
**변경이유**
현재 모모는 “비밀번호를 1~10자 사이로 입력해 주세요. 사용 가능한 문자는 알파벳, 숫자, 특수문자(!@#$%)입니다.” 라고 적혀있습니다.
이 안내 문구로 인해 사용자들은 비밀번호를 길게 입력해야 한다고 생각하여, 긴 비밀번호를 입력하는 경향을 보였습니다.
때문에 비밀번호를 `4자리 숫자`로 제한하여 입력 과정을 단순화했습니다.
자세한 내용은 @Yoonkyoungme이 작성한 [해당 기능에 대한 문서](https://paper-mass-5ff.notion.site/4f4d0d9cfde84d0cb17f2537b7815069)를 참고해 주세요~

[BE] 비밀번호 검증 로직 변경

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.common.js

- resolves: #347 
Webpack은 기본적으로 src 디렉토리의 파일만 처리하므로, public 디렉토리에 있는 favicon 파일들은 처리 대상에서 제외됩니다.
그 결과, 빌드된 HTML 파일에서 favicon 파일의 경로가 올바르지 않게 설정되어 해당 파일을 불러올 수 없는 오류가 발생합니다.
아래 사진처럼 [배포된 사이트](https://www.momonow.kr/)에서 favicon이 적용되지 않는 문제가 발생하였습니다.
여러 favicon 파일을 처리해야 하므로, [`CopyWebpackPlugin`](https://webpack.js.org/plugins/copy-webpack-plugin/)을 사용하여 모든 favicon 파일을 빌드 디렉토리로 복사하도록 설정했습니다. 
```bash
npm install copy-webpack-plugin --save-dev
```
```jsx
const CopyWebpackPlugin = require('copy-webpack-plugin');
// plugins 배열에 추가
new CopyWebpackPlugin({
patterns: [
{ from: 'public/assets/favicons', to: 'assets/favicons' }
],
})
```
`build` 디렉토리의 파일을 S3에 수동으로 배포하여 테스트해보았습니다.
배포된 사이트에서 아래의 이미지와 같이 favicon이 잘 표시되는 것을 확인하였습니다.👏
자세한 내용은 [작업 현황 정리 …

[FE] CopyWebpackPlugin을 사용하여 favicon 적용 문제 해결

---

backend/src/main/java/kr/momo/config/DataSourceConfig.java
backend/src/main/java/kr/momo/config/RoutingDataSource.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java

- resolves: #357 
DB 트래픽을 rds로 변경하라는 요구사항을 반영하기 위해 읽기, 쓰기 쿼리별로 트래픽을 분리하였습니다
현재 컨텍스트에 따라 처리할 datasource를 동적으로 결정해도록 하는 Spring의 추상 클래스입니다.
RountingTable 형태로 datasource를 관리하며 `RoutingDataSource` 객체에 구현하여 datasource 결정 조건을 정해주었습니다.
datasource는 `@Transactional` readOnly 설정이 걸려있는 경우 replica datasource에 해당하는 key를 할당하도록 설정해주었습니다.
스프링의 기본 구현은 트랜잭션 시작시 커넥션을 확보하기 위해 DataSource를 결정 짓기 위해 연결합니다.
`LazyConnectionDataSourceProxy` 객체의 경우 DataSource 연결을 지연 로딩하여 필요할때만 연결을 생성합니다.
`RoutingDataSource`의 키 결정 조건인`TransactionSynchronizationManager.isCurrentTransactionReadOnly()`는 트랜잭션이 시작된 이후에 알 수 있기에 `LazyConnectionDataSourceProxy`를 사용하였습니다.
[Baeldung - A Guide to Spring AbstractRoutingDatasource](https://www.baeldung.com/spring-abstract-routing-data-source)
[Spring Docs - …

[BE] DB read, write 쿼리 트래픽을 분리해요

---

backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
backend/src/main/java/kr/momo/domain/attendee/Attendee.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java

- resolves: #368 
이전 비밀번호에 대해 암호화를 적용하는 코드를 구현하였습니다 :)

[BE] 비밀번호 마이그레이션 추가

---

backend/src/main/java/kr/momo/config/RoutingDataSource.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java

- resolves: #373 
`@Transactional`을 붙히지 않아 우선으로 날아간 select 쿼리로 인해 replica로 datasource가 설정된 상태에서 update 쿼리가 날아가 에러가 발생했어요.

[BE] replica로 업데이트 쿼리 날아가던 오류 수정

---

frontend/package.json
frontend/webpack.common.js

- resolves: #377 
깃허브 워크플로우에서 webpack-bundle-analyzer가 실행되어, job이 끝나지 않았던 문제를 해결했어요.

[FE] 깃허브 워크플로우에서 webpack-bundle-analyzer가 실행됐던 문제 해결

---

.github/workflows/frontend-ci.yml

- resolves: #379 
> 카카오 SDK 스크립트에 async속성은 추가하지 않기로 결정되었습니다. 이유는 이슈에 추가적으로 등록해두었습니다.
- async 속성으로 인해 SDK와 연관된 컴포넌트 로직이 SDK보다 먼저 불러와지는 현상으로 인해 에러가 발생하여 async 속성은 추가하지 않기로 결정되었습니다.

[ALL] frontend CI 수정

---

frontend/src/components/Schedules/Schedules.styles.ts
frontend/src/mocks/meeting/meetingHandlers.ts
frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
frontend/src/pages/MeetingTimePickPage/index.tsx

[FE] BottomFixedButton 버그 수정

---

frontend/src/assets/images/attendeeCheck.svg
frontend/src/assets/images/check.svg
frontend/src/assets/images/exclamation.svg
frontend/src/components/_common/Toast/Toast.stories.tsx
frontend/src/components/_common/Toast/Toast.styles.ts
frontend/src/components/_common/Toast/Toast.type.ts
frontend/src/components/_common/Toast/ToastContainer.tsx
frontend/src/components/_common/Toast/ToastList/ToastList.styles.ts
frontend/src/components/_common/Toast/ToastList/ToastList.tsx
frontend/src/components/_common/Toast/index.tsx
frontend/src/contexts/ToastProvider.tsx
frontend/src/hooks/useToast/useToast.ts
frontend/src/index.tsx

- resolves: #387 
- 사용자에게 피드백을 전달해줄 수 있는 토스트 UI를 구현했습니다.
모모 서비스에서 토스트 UI를 사용할 때, 위 이미지처럼 3가지 상황에서 사용할 수 있습니다. (성공, 경고, 기본)
위 토스트 UI 디자인을 끝낸 후, 아래와 같은 고민들을 하며 토스트 UI를 구현했습니다.
토스트 컴포넌트는 최대한 UI만 그리는 책임을 가지도록 구현했습니다. 그 이유는 아래와 같습니다.
- 스토리북으로 테스트하기 용이
- 먄약 토스트 컴포넌트 내부에서 특정 시간이 지난 후 사라지게 하는 책임이나 사라질 때 애니메이션을 적용하도록 하는 책임을 부여한다면 스토리북으로 UI 테스트를 진행하기 힘들 것이라 판단했습니다.
- 그래서, 최대한 UI와 관련된 책임만 가지도록 구현했어요.
- 하나의 책임만 가지니, 가독성과 유지보수 측면에서도 좋음
```tsx
// 토스트 컴포넌트는 UI를 보여주는 책임만 가질 수 있도록 최대한 책임을 분리하고 스토리북을 활용한 UI 테스트를 쉽게할 수 있도록 한다.(@해리)
export default function Toast({ isOpen, type = 'default', message }: ToastProps) {
const ToastIcon = iconMap[type];
return (
<div css={s_toastContainer(isOpen)}>
{type !== 'default' && (
<div css={[s_iconContainer, s_iconBackgroundColor(type)]}>
{ToastIcon && <ToastIcon …
```

[FE] 토스트 UI 구현

---

backend/src/main/java/kr/momo/config/RoutingDataSource.java
backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
backend/src/main/java/kr/momo/service/attendee/AttendeeService.java

- resolves: #376 
비밀번호 마이그레이션을 완료하여 이젠 사용하지 않는 비밀번호 마이그레이션 코드를 삭제하였습니다.
현재 Datasource는 쿼리가 발생하는 시점에 Source DB와 Replica DB를 동적으로 선택하는데요.
이때 연결된 Datasource가 무엇인지 알고자 로그로 남겨두었는데요. 
`AbstractRoutingDataSource`가 스레드가 변경되어 데이터베이스 작업을 시작할 때마다 어떤 데이터소스를 사용할지 결정하기 위해 determineCurrentLookupKey()를 호출하게 되어 의도한 동작과 다를 때도 로그를 찍히는 것을 발견하게 되었습니다.
불필요하게 많아지는 로그를 방지하기 위해 debug 레벨로 로그를 남기도록 수정하였습니다 :)

[BE] 비밀번호 마이그레이션 로직 삭제

---

.github/workflows/backend-dev-cd.yml

- resolves: #370 
dev 환경의 모니터링 변경으로 backend-dev-cd파일을 수정했습니다.
dev 환경을 배포할 때,  momo-dev-api 이미지만 최신화하여 재시작하고 그 외, 모니터링 관련 컨테이너는 그대로 두도록 수정했습니다.
그외 모니터링 컨테이너 목록
* promtail
* loki
* node_exporter
* prometheus
* grafana
**질문1)**
`docker-compose.yml` 파일은 현재 `momo-dev `인스턴스에 위치합니다.
이 `momo-config 서브모듈`로 옮겨서 인스턴스 내부에서가 아닌, 로컬에서도 관리할 수 있게 수정해야 하나 고민입니다.
서브모듈에서 관리한다면, 인스턴스에 직접 접속하는 번거로움도 줄일 수 있고 문제 발생 시 빠르게 롤백할 수 있는 장점 등이 있는 것 같습니다.
이 부분에 대해서 팀원들의 의견이 궁금합니다~
**질문2)**
`momo-dev-api` 이미지만 재실행하는 것이 맞을까요? 
다른 모니터링 관련 컨테이너(`promtail`, `grafana` 등..)는 배포 시에 업데이트될 필요가 없어서 이렇게 했습니다.
그런데 제가 예상하지 못한 문제점이 있을 수도 있으니, 확인 부탁드립니다.

[BE] dev환경 배포 방식 수정

---

frontend/jest.config.js
frontend/package.json
frontend/src/hooks/useCalendar/useCalendar.test.ts
frontend/src/hooks/useCalendar/useCalendar.ts
frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
frontend/src/hooks/useCalendar/useCalendar.utils.ts

- resolves: #382 
- jsDoc을 삭제하고 jest, RTL을 활용해서 달력 데이터 생성 로직에 대한 테스트 코드를 작성했습니다.
- 현재 달력 데이터를 생성하는 모듈은 이전 달, 다음 달 데이터를 함께 생성하게 됩니다.  
-> UI에서 이전 달, 다음 달 데이터를 활용할 수도 있기에 유연하게 해당 모듈을 사용하기 위해서 이 방식으로 구현했었습니다.
-> 현재 저희 서비스에서는 사용하고 있지는 않지만, 학습 겸 어떻게 더 달력 데이터를 유연하게 만들 수 있을까 하다가 이 방식을 떠올렸고 구현했습니다. 
- 주, 월 별 달력 데이터를 올바르게 생성하는지 확인합니다.
- 생성된 달력 데이터들의 날짜가 올바른 상태(prev, current, next)를 가지는지 확인합니다.
- 달력 데이터를 변경할 수 있는 책임을 가집니다.
- 이전 달, 다음 달로 이동했을 때 데이터가 이에 맞게 올바르게 변경되는지 테스트 합니다. 
달력 로직이 생각보다 복잡해서 시간이 많이 소요되었네요...원래는 스토리북도 더 직관적으로 확인할 수 있도록 날짜 상태에 따른 날짜 UI도 구분해서 UI 테스트를 진행하려고 했는데 이슈를 한 번 더 파야할 것 같아요! 테스트 초록불이 뜨니 안전한 달력을 만들었다는 느낌이 들어 안심이 되네요..ㅎ 
자바스크립트는 달(Month)의 인덱스를 0부터 시작해서 테스트 코드를 작성할 때 1씩 빼주고 테스트를 진행했습니다. UI영역에서 현재 달에 +1을 해준 것을 확인할 수 있는데, 0부터 시작하는 예외를 처리해주기 위함이었습니다! 리뷰하실 때, 참고바랍니다 🙏🙏🙏

[FE] 달력 테스트 코드 작성

---

.github/workflows/backend-prod-cd.yml

- resolves: #401 
기존 설정은 이중화된 배포 서버의 두 개의 self hosted runner를 `prod`라는 하나의 label로 실행하려고 했습니다.
github workflow의 label은 특정 러너로 실행하는 것에 목적이 있습니다. 두 runner 중 하나만 실행되고 있었습니다.
각 runner의 label을 나누고, 워크플로의 매트릭스 전략을 통해 하나의 job을 여러 번 실행하는 방법을 사용하여 문제를 해결합니다.
기존 워크플로는 모든 도커 컨테이너를 중단한 후 `docker run`으로 배포하였습니다. 하지만 배포 서버를 모니터링하기 위한 컨테이너들이 추가 되었고 도커 컴포즈로 관리하게 되었습니다. 이에 맞게 배포 작업을 수정했습니다.
개발 서버 CD 워크플로가 먼저 잘 작동한 것을 확인했습니다.
로컬에서 하나의 저장소에 두 runner가 동작하는지 매트릭스 전략을 테스트해봤습니다.
참고 자료
- [about-workflows#using-a-matrix](https://docs.github.com/ko/actions/writing-workflows/about-workflows#using-a-matrix)
- [running-variations-of-jobs-in-a-workflow](https://docs.github.com/ko/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow)
- …

[BE] 배포 서버 CD 작업이 하나의 runner만 실행되는 문제와 앱을 제외한 컨테이너가 내려가는 문제를 해결

---

frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.tsx

- resolves: #399 
- 약속 type이 DATETIME일 때만 필터링 기능을 렌더링 하도록 구현
날짜만 선택 기능으로 추천받을 때 500에러 발생 및 "길게 만나고 싶어요"라는 필터링 컨텍스트가 "시간"에만 필요한 기능이기 때문에 날짜만 선택 시 불필요한 필터링 기능이라 판단하고 제거

[FE] 날짜만 입력 시, 약속 추천 필터링 기능 제거

---

.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml

- resolves: #407 
**🚨 dev, prod 모두 배포할 때마다 같은 자바스크립트 파일이 중복으로 업로드 되는 문제 발생**
**🚨 prod에 배포할 때마다, dev에 있는 자바스크립트 파일을 계속해서 가져오는 문제 발생**
원인은, dev와 prod 배포 모두 동일한 인스턴스를 사용하고, 같은 폴더인 frontend/dist를 사용하기 때문이었습니다. 해당 폴더를 배포 자동화를 위해 사용할 때마다 자바스크립트 파일들이 쌓이고, 해당 파일들을 aws와 싱크를 맞춥니다. 이 때, dev에 배포하든 prod에 배포하든 서로의 배포에 영향을 주게 됩니다. 그래서 깃허브 임시 저장소(artifacts)에 있는 리소스들을 다운로드 받기 전 이전 버전 배포를 위해 사용되었던 dist 폴더 내부 모든 파일들을 삭제하도록 하는 step을 추가했습니다. 아래는 추가된 step입니다.
```sh
- name: 기존 dist 폴더 내부에 있던 이전 버젼의 dist 폴더 내부 모든 파일을 삭제해요
working-directory: ./frontend/
run: |
rm -rf dist/*
```

[ALL] 자바스크립트 번들 파일이 중복으로 생기는 문제 해결

---

.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml
frontend/src/mocks/meeting/data/mySchedule.json

- resolves: #407 
> 관련 해결 PR 링크 : https://github.com/woowacourse-teams/2024-momo/pull/408
워크플로우 변경사항을 develop 브랜치에 동기화하기 위한 PR입니다.

[ALL] 프론트엔드 워크플로우 변경사항 develop 브랜치에 적용

---

.github/workflows/backend-prod-cd.yml

- resolves: #412 
프로덕션 서버(`prod-a`, `prod-b`)에 무중단 배포를 적용합니다.
nginx와 docker 컨테이너를 활용한 Blue/Green 전략을 사용하며, 인스턴스 내에서 컨테이너 두 개를 실행하고, 새로운 컨테이너에 이상이 없다면 `proxy_pass`를 전환시킨 후 기존 컨테이너를 종료하는 형태로 동작합니다.
```bash
echo "0. 현재 실행 중인 컨테이너 목록 확인"
show_docker_ps
echo "1. Green 포트 결정"
determine_port
echo "2. Green 컨테이너 실행"
run_green_container $new_was_port $new_actuator_port
echo "3. Green Health Check"
green_health_check $new_actuator_port
echo "4. nginx 포트 재설정 -> nginx reload"
nginx_reload $new_was_port $new_actuator_port $past_was_port $past_actuator_port
echo "5. Blue 컨테이너 stop -> rm"
stop_blue_container $past_was_port
echo "6. 배포 완료"
finalize $new_was_port
```
전체 플로우는 위와 같으며, 스크립트 상세 구현은 서브모듈을 참고해 주세요.
`Connection: keep-alive`에서 nginx가 TCP 커넥션을 처리하는 방식 때문에 `nginx reload` 시 약 0.1~0.2초의 다운타임이 발생합니다. …

[BE] 프로덕션 서버 무중단 배포 환경 구축

---

frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/MeetingCreationConfirmModal.styles.ts
frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/index.tsx
frontend/src/pages/CreateMeetingPage/index.tsx

- resolves: #406 
[약속 생성 시 퍼널 패턴을 도입하는 과정](https://github.com/woowacourse-teams/2024-momo/pull/356)에서 사라졌던 '약속 생성 확인 모달'을 복구하였습니다.
'약속 생성 확인 모달'은 `CreateMeetingPage` 하위 컴포넌트(`MeetingCreationConfirmModal`)로 분리하였습니다. 
<div align="center">
</div>

[FE] 약속 생성 확인 모달 복구

---

frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
frontend/src/stores/servers/user/mutations.ts

- resolves: #425 
- 로그인 시 라우팅 경로 `/meeting/:uuid` -> `/meeting/:uuid/register`로 변경
- ConfirmModal 날짜만 선택 옵션 사용 시에도 동작하도록 수정
https://github.com/user-attachments/assets/249775de-2219-4487-bc9f-537f4d4acdd7
없습니다~!

[FE] 달력 확정 페이지 ConfirmModal 추가 및 로그인 후 라우팅 경로 수정

---

frontend/src/components/ComponentCarousel/index.tsx
frontend/src/components/_common/Buttons/BottomFixedButton/BottomFixedButton.styles.ts
frontend/src/constants/inputFields.ts

[FE] 약속 생성 플레이스홀더, 캐러셀 이동 속도 수정

---

frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
frontend/src/stores/servers/user/mutations.ts

* refactor: 로그인 시, 등록 페이지로 이동하도록 라우팅 경로 수정
* feat: 날짜만 조회 선택 후 확정 페이지 이동 시 ConfirmModal을 띄우도록 추가
- resolves: #426

[FE] 달력 확정 페이지에서도 약속 잠금 모달을 사용할 수 있도록 수정
